# Comment
GXX = g++
CPP_FILES = input_validation.cpp
FLAG = -c -g -Wall -std=c++17
PROGRAM = input_validation.exe

compile:
#	g++ input_validation.cpp -o input_validation
	$(GXX) $(FLAGS) $(CPP_FILES) -o $(PROGRAM)

run:
#	./input_validation
	./$(PROGRAM)

clean:
#	rm -f input_validation *.o
	rm -f $(PROGRAM) *.o